"""Pinned private observer for GLiNER 0.2.28 StreamingSpan sessions.

Only the reference environment should execute this module's observer. It uses
the verified private ``_session_cache`` solely to copy score and coordinate
metadata; it never mutates a ``CacheState`` or retains model embeddings.
"""

from __future__ import annotations

import json
import math
import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from importlib.metadata import PackageNotFoundError, version
from types import MappingProxyType
from typing import Any

import numpy as np

from streamner_commit.types import (
    PublicEntity,
    SnapshotStep,
    SpanBoundary,
    SpanScoreUpdate,
    UpdateKind,
)

PINNED_GLINER_VERSION = "0.2.28"
_PUBLIC_SCORE_TOLERANCE = 2e-5
_RAW_SCORE_TOLERANCE = 1e-6


class ObserverInvariantError(RuntimeError):
    """Raised when the pinned reference model violates an observed invariant."""


@dataclass(frozen=True, slots=True)
class _ForwardCapture:
    logits: np.ndarray
    span_idx: np.ndarray
    span_mask: np.ndarray


@dataclass(frozen=True, slots=True)
class ObservedAppend:
    """One public snapshot plus the raw candidates generated by that append."""

    snapshot: SnapshotStep
    span_updates: tuple[SpanScoreUpdate, ...]
    merged_span_logits: Mapping[SpanBoundary, tuple[float, ...]] = field(hash=False)
    validated_public_score_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe observer record."""
        merged = [
            {
                "start_word": boundary.start_word,
                "end_word": boundary.end_word,
                "logits": list(logits),
            }
            for boundary, logits in sorted(self.merged_span_logits.items())
        ]
        return {
            "snapshot": self.snapshot.to_dict(),
            "span_updates": [update.to_dict() for update in self.span_updates],
            "merged_span_logits": merged,
            "validated_public_score_count": self.validated_public_score_count,
        }


def _require_identifier(name: str, value: str) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{name} must be a string")
    if not value.strip():
        raise ValueError(f"{name} must not be blank")
    return value


def _ordered_labels(labels: Sequence[str]) -> tuple[str, ...]:
    if isinstance(labels, str | bytes) or not isinstance(labels, Sequence):
        raise TypeError("labels must be a sequence of strings")
    result = tuple(_require_identifier("label", label) for label in labels)
    if not result:
        raise ValueError("labels must not be empty")
    if len(result) != len(set(result)):
        raise ValueError("labels must be unique and ordered")
    return result


def _probability_threshold(value: float) -> float:
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise TypeError("threshold must be a real number")
    result = float(value)
    if not math.isfinite(result) or not 0.0 <= result <= 1.0:
        raise ValueError("threshold must be finite and between 0 and 1")
    return result


def _sigmoid(value: float) -> float:
    if value >= 0.0:
        return 1.0 / (1.0 + math.exp(-value))
    exponential = math.exp(value)
    return exponential / (1.0 + exponential)


def _detach_cpu_array(value: object, *, name: str) -> np.ndarray:
    """Detach and copy one hooked tensor immediately, retaining no graph."""
    detach = getattr(value, "detach", None)
    if not callable(detach):
        raise ObserverInvariantError(f"hooked {name} is not a detachable tensor")
    detached = detach()
    cpu = getattr(detached, "cpu", None)
    if not callable(cpu):
        raise ObserverInvariantError(f"hooked {name} cannot be copied to CPU")
    cpu_value = cpu()
    tolist = getattr(cpu_value, "tolist", None)
    if not callable(tolist):
        raise ObserverInvariantError(f"hooked {name} cannot be converted to host values")
    return np.asarray(tolist()).copy()


def _capture_forward_output(output: object) -> _ForwardCapture:
    values: dict[str, np.ndarray] = {}
    for name in ("logits", "span_idx", "span_mask"):
        value = getattr(output, name, None)
        if value is None:
            raise ObserverInvariantError(f"StreamingSpanModel output is missing {name}")
        values[name] = _detach_cpu_array(value, name=name)

    logits = values["logits"]
    if logits.ndim == 4:
        logits = logits.reshape(logits.shape[0], -1, logits.shape[-1])
    elif logits.ndim != 3:
        raise ObserverInvariantError(
            "hooked logits must have shape (batch, spans, classes) or "
            "(batch, words, widths, classes)"
        )
    if logits.shape[0] != 1:
        raise ObserverInvariantError("observer requires a single-session forward batch")
    if not np.issubdtype(logits.dtype, np.number):
        raise ObserverInvariantError("hooked logits must be numeric")
    logits = logits.astype(np.float64, copy=False)
    if not np.isfinite(logits).all():
        raise ObserverInvariantError("hooked logits contain non-finite values")

    span_idx = values["span_idx"]
    if span_idx.ndim < 3 or span_idx.shape[0] != 1 or span_idx.shape[-1] != 2:
        raise ObserverInvariantError("hooked span_idx must have shape (1, ..., 2)")
    if not np.issubdtype(span_idx.dtype, np.integer):
        raise ObserverInvariantError("hooked span_idx must contain integers")
    span_idx = span_idx.reshape(1, -1, 2).astype(np.int64, copy=False)

    span_mask = values["span_mask"]
    if span_mask.ndim < 2 or span_mask.shape[0] != 1:
        raise ObserverInvariantError("hooked span_mask must have shape (1, ...)")
    if not (np.issubdtype(span_mask.dtype, np.bool_) or np.issubdtype(span_mask.dtype, np.integer)):
        raise ObserverInvariantError("hooked span_mask must be boolean or integral")
    if not np.isin(span_mask, (0, 1)).all():
        raise ObserverInvariantError("hooked span_mask values must be zero or one")
    span_mask = span_mask.reshape(1, -1).astype(np.bool_, copy=False)

    if logits.shape[1] != span_idx.shape[1] or logits.shape[1] != span_mask.shape[1]:
        raise ObserverInvariantError(
            "hooked logits, span_idx, and span_mask describe different candidate counts"
        )
    return _ForwardCapture(logits=logits, span_idx=span_idx, span_mask=span_mask)


def _host_values(value: object, *, name: str) -> object:
    if hasattr(value, "detach"):
        return _detach_cpu_array(value, name=name)
    return value


def _score_vector(value: object, *, name: str) -> tuple[float, ...]:
    host = _host_values(value, name=name)
    try:
        array = np.asarray(host, dtype=np.float64)
    except (TypeError, ValueError) as error:
        raise ObserverInvariantError(f"{name} is not a numeric score vector") from error
    if array.ndim != 1 or array.size == 0:
        raise ObserverInvariantError(f"{name} must be a nonempty one-dimensional vector")
    if not np.isfinite(array).all():
        raise ObserverInvariantError(f"{name} contains non-finite values")
    return tuple(float(item) for item in array)


def _copy_merged_state(
    state: object,
    *,
    label_count: int,
) -> Mapping[SpanBoundary, tuple[float, ...]]:
    raw_state = getattr(state, "span_logits", None)
    if not isinstance(raw_state, Mapping):
        raise ObserverInvariantError("CacheState.span_logits is not a mapping")
    copied: dict[SpanBoundary, tuple[float, ...]] = {}
    for raw_boundary, raw_scores in raw_state.items():
        if (
            not isinstance(raw_boundary, tuple)
            or len(raw_boundary) != 2
            or any(isinstance(item, bool) or not isinstance(item, int) for item in raw_boundary)
        ):
            raise ObserverInvariantError("CacheState.span_logits has an invalid boundary key")
        boundary = SpanBoundary(raw_boundary[0], raw_boundary[1])
        scores = _score_vector(raw_scores, name=f"span_logits[{raw_boundary}]")
        if len(scores) != label_count:
            raise ObserverInvariantError(
                "CacheState span score width does not equal the ordered label count"
            )
        copied[boundary] = scores
    return MappingProxyType(copied)


def _single_public_row(output: object) -> Sequence[object]:
    if isinstance(output, str | bytes) or not isinstance(output, Sequence):
        raise ObserverInvariantError("public inference did not return a batch sequence")
    if len(output) != 1:
        raise ObserverInvariantError("observer inference must return exactly one batch row")
    row = output[0]
    if isinstance(row, str | bytes) or not isinstance(row, Sequence):
        raise ObserverInvariantError("public inference row is not an entity sequence")
    return row


def _field(entity: Mapping[str, object], primary: str, alternate: str | None = None) -> object:
    if primary in entity:
        return entity[primary]
    if alternate is not None and alternate in entity:
        return entity[alternate]
    raise ObserverInvariantError(f"public entity is missing {primary}")


def _public_entities(output: object, text: str) -> tuple[PublicEntity, ...]:
    result: list[PublicEntity] = []
    for value in _single_public_row(output):
        if isinstance(value, PublicEntity):
            entity = value
        elif isinstance(value, Mapping):
            try:
                entity = PublicEntity(
                    start_char=_field(value, "start_char", "start"),  # type: ignore[arg-type]
                    end_char=_field(value, "end_char", "end"),  # type: ignore[arg-type]
                    label=_field(value, "label"),  # type: ignore[arg-type]
                    text=_field(value, "text"),  # type: ignore[arg-type]
                    score=_field(value, "score"),  # type: ignore[arg-type]
                )
            except (TypeError, ValueError) as error:
                raise ObserverInvariantError(f"invalid public entity: {error}") from error
        else:
            raise ObserverInvariantError("public entity is not a mapping or PublicEntity")
        if entity.end_char > len(text) or text[entity.start_char : entity.end_char] != entity.text:
            raise ObserverInvariantError("public entity offsets do not match accumulated text")
        result.append(entity)
    return tuple(result)


def _state_coordinates(
    state: object,
) -> tuple[str, tuple[str, ...], tuple[int, ...], tuple[int, ...]]:
    text = getattr(state, "text", None)
    tokens = getattr(state, "tokens", None)
    starts = getattr(state, "char_starts", None)
    ends = getattr(state, "char_ends", None)
    if not isinstance(text, str):
        raise ObserverInvariantError("CacheState.text is not a string")
    if not isinstance(tokens, list) or not all(isinstance(token, str) for token in tokens):
        raise ObserverInvariantError("CacheState.tokens is not a list of strings")
    if not isinstance(starts, list) or not isinstance(ends, list):
        raise ObserverInvariantError("CacheState character offsets are not lists")
    if len(tokens) != len(starts) or len(tokens) != len(ends):
        raise ObserverInvariantError("CacheState word and character metadata lengths differ")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in (*starts, *ends)):
        raise ObserverInvariantError("CacheState character offsets are not integers")
    for index, (start, end) in enumerate(zip(starts, ends, strict=True)):
        if not 0 <= start < end <= len(text):
            raise ObserverInvariantError(f"CacheState has invalid offsets for word {index}")
        if text[start:end] != tokens[index]:
            raise ObserverInvariantError(
                f"CacheState token {index} does not match its character offsets"
            )
    return text, tuple(tokens), tuple(starts), tuple(ends)


def _validate_public_scores(
    entities: tuple[PublicEntity, ...],
    *,
    labels: tuple[str, ...],
    starts: tuple[int, ...],
    ends: tuple[int, ...],
    merged: Mapping[SpanBoundary, tuple[float, ...]],
) -> int:
    label_indices = {label: index for index, label in enumerate(labels)}
    validated = 0
    for entity in entities:
        if entity.label not in label_indices:
            raise ObserverInvariantError(
                f"public entity label {entity.label!r} is outside the ordered label set"
            )
        boundaries = [
            SpanBoundary(start_word, end_word)
            for start_word, start in enumerate(starts)
            for end_word, end in enumerate(ends)
            if start_word <= end_word and start == entity.start_char and end == entity.end_char
        ]
        if len(boundaries) != 1 or boundaries[0] not in merged:
            continue
        boundary = boundaries[0]
        raw_logit = merged[boundary][label_indices[entity.label]]
        expected = _sigmoid(raw_logit)
        if not math.isclose(
            entity.score,
            expected,
            rel_tol=_PUBLIC_SCORE_TOLERANCE,
            abs_tol=_PUBLIC_SCORE_TOLERANCE,
        ):
            raise ObserverInvariantError(
                f"public score {entity.score:.8f} does not match sigmoid(raw logit) "
                f"{expected:.8f} for {boundary.to_tuple()} / {entity.label!r}"
            )
        validated += 1
    return validated


class StreamingSpanObserver:
    """Observe raw candidate updates for one newly-created reference session."""

    def __init__(
        self,
        model: object,
        *,
        run_id: str,
        example_id: str,
        session_id: str,
        labels: Sequence[str],
        threshold: float = 0.5,
        flat_ner: bool = True,
        multi_label: bool = False,
        verify_reference: bool = True,
        clock: Callable[[], float] = time.perf_counter,
    ) -> None:
        self.model = model
        self.run_id = _require_identifier("run_id", run_id)
        self.example_id = _require_identifier("example_id", example_id)
        self.session_id = _require_identifier("session_id", session_id)
        self.labels = _ordered_labels(labels)
        self.threshold = _probability_threshold(threshold)
        if not isinstance(flat_ner, bool) or not isinstance(multi_label, bool):
            raise TypeError("flat_ner and multi_label must be booleans")
        self.flat_ner = flat_ner
        self.multi_label = multi_label
        if not callable(clock):
            raise TypeError("clock must be callable")
        self._clock = clock
        self._merged_span_logits: Mapping[SpanBoundary, tuple[float, ...]] = MappingProxyType({})
        self._accumulated_text = ""
        self._last_step: int | None = None
        self._closed = False

        if verify_reference:
            self._verify_reference_model()
        self._internal_model = getattr(model, "model", None)
        register = getattr(self._internal_model, "register_forward_hook", None)
        if not callable(register):
            raise TypeError("model.model does not support forward hooks")
        self._register_forward_hook: Callable[..., Any] = register
        cache = getattr(model, "_session_cache", None)
        get_state = getattr(cache, "get", None)
        if not callable(get_state):
            raise TypeError("model._session_cache.get is unavailable")
        self._session_cache = cache
        self._get_session_state: Callable[..., Any] = get_state
        if get_state(self.session_id) is not None:
            raise ValueError("observer requires a new, empty session ID")

    def _verify_reference_model(self) -> None:
        try:
            installed = version("gliner")
        except PackageNotFoundError as error:
            raise RuntimeError("GLiNER is not installed in this environment") from error
        if installed != PINNED_GLINER_VERSION:
            raise RuntimeError(
                f"observer requires GLiNER {PINNED_GLINER_VERSION}, found {installed}"
            )
        if type(self.model).__name__ != "StreamingSpanGLiNER":
            raise TypeError("observer requires the concrete StreamingSpanGLiNER wrapper")
        internal = getattr(self.model, "model", None)
        if type(internal).__name__ != "StreamingSpanModel":
            raise TypeError("observer hook target must be the concrete StreamingSpanModel")

    def _abort_session(self) -> None:
        self._closed = True
        self.model.clear_session(self.session_id)  # type: ignore[attr-defined]

    def append(self, chunk: str, *, step: int) -> ObservedAppend:
        """Append one nonblank chunk and capture its exact generated candidates."""
        if self._closed:
            raise RuntimeError("observer session is closed")
        if not isinstance(chunk, str):
            raise TypeError("chunk must be a string")
        if not chunk.strip():
            raise ValueError("observer append requires a non-whitespace chunk")
        if isinstance(step, bool) or not isinstance(step, int):
            raise TypeError("step must be an integer")
        if step < 0:
            raise ValueError("step must be nonnegative")
        if self._last_step is not None and step <= self._last_step:
            raise ValueError("step must increase for each append")

        captures: list[_ForwardCapture] = []

        def hook(_module: object, _inputs: object, output: object) -> None:
            captures.append(_capture_forward_output(output))

        handle = self._register_forward_hook(hook)
        expected_text = self._accumulated_text + chunk
        started = self._clock()
        try:
            public_output = self.model.inference(  # type: ignore[attr-defined]
                [chunk],
                list(self.labels),
                flat_ner=self.flat_ner,
                threshold=self.threshold,
                multi_label=self.multi_label,
                batch_size=1,
                session_id=[self.session_id],
            )
            elapsed_ms = (self._clock() - started) * 1000.0
        except Exception:
            self._abort_session()
            raise
        finally:
            handle.remove()

        try:
            if len(captures) != 1:
                raise ObserverInvariantError(
                    "expected exactly one StreamingSpanModel forward hook, "
                    f"observed {len(captures)}"
                )
            capture = captures[0]
            if capture.logits.shape[-1] != len(self.labels):
                raise ObserverInvariantError(
                    "hooked class-vector width does not equal the ordered label count"
                )

            state = self._get_session_state(self.session_id)
            if state is None:
                raise ObserverInvariantError("session cache has no state after inference")
            if tuple(getattr(state, "labels", ())) != self.labels:
                raise ObserverInvariantError(
                    "CacheState labels differ from the observer label order"
                )
            state_text, tokens, starts, ends = _state_coordinates(state)
            if state_text != expected_text:
                raise ObserverInvariantError("CacheState text differs from exact appended text")
            merged = _copy_merged_state(state, label_count=len(self.labels))
            public_entities = _public_entities(public_output, state_text)

            updates: list[SpanScoreUpdate] = []
            generated_boundaries: set[SpanBoundary] = set()
            row_mask = capture.span_mask[0]
            for raw_boundary, raw_logits in zip(
                capture.span_idx[0, row_mask],
                capture.logits[0, row_mask],
                strict=True,
            ):
                boundary = SpanBoundary(int(raw_boundary[0]), int(raw_boundary[1]))
                if boundary in generated_boundaries:
                    raise ObserverInvariantError(
                        f"forward generated duplicate boundary {boundary.to_tuple()}"
                    )
                generated_boundaries.add(boundary)
                if boundary.end_word >= len(tokens):
                    raise ObserverInvariantError(
                        f"forward boundary {boundary.to_tuple()} exceeds visible words"
                    )

                logits = tuple(float(value) for value in raw_logits)
                probabilities = tuple(_sigmoid(value) for value in logits)
                top_index = max(range(len(probabilities)), key=probabilities.__getitem__)
                top_probability = probabilities[top_index]
                remaining = probabilities[:top_index] + probabilities[top_index + 1 :]
                second_probability = max(remaining, default=0.0)
                previous = self._merged_span_logits.get(boundary)
                previous_top_probability = (
                    None if previous is None else max(_sigmoid(value) for value in previous)
                )
                kind: UpdateKind = "new" if previous is None else "rescore"
                start_char = starts[boundary.start_word]
                end_char = ends[boundary.end_word]
                updates.append(
                    SpanScoreUpdate(
                        run_id=self.run_id,
                        example_id=self.example_id,
                        step=step,
                        chunk=chunk,
                        visible_char_count=len(state_text),
                        visible_word_count=len(tokens),
                        start_word=boundary.start_word,
                        end_word=boundary.end_word,
                        start_char=start_char,
                        end_char=end_char,
                        span_text=state_text[start_char:end_char],
                        logits=logits,
                        probs=probabilities,
                        top_label_index=top_index,
                        top_label=self.labels[top_index],
                        top_probability=top_probability,
                        second_probability=second_probability,
                        label_margin=top_probability - second_probability,
                        previous_top_probability=previous_top_probability,
                        top_probability_delta=(
                            None
                            if previous_top_probability is None
                            else top_probability - previous_top_probability
                        ),
                        update_kind=kind,
                        tail_distance_words=(len(tokens) - 1) - boundary.end_word,
                    )
                )

                merged_logits = merged.get(boundary)
                if merged_logits is None or not np.allclose(
                    logits,
                    merged_logits,
                    rtol=0.0,
                    atol=_RAW_SCORE_TOLERANCE,
                ):
                    raise ObserverInvariantError(
                        "merged CacheState does not contain hooked scores for "
                        f"{boundary.to_tuple()}"
                    )

            validated_public_scores = _validate_public_scores(
                public_entities,
                labels=self.labels,
                starts=starts,
                ends=ends,
                merged=merged,
            )
            snapshot = SnapshotStep(
                run_id=self.run_id,
                example_id=self.example_id,
                step=step,
                chunk=chunk,
                accumulated_text=state_text,
                visible_char_count=len(state_text),
                visible_word_count=len(tokens),
                elapsed_ms=elapsed_ms,
                public_entities=public_entities,
            )
        except Exception:
            self._abort_session()
            raise

        self._merged_span_logits = merged
        self._accumulated_text = state_text
        self._last_step = step
        return ObservedAppend(
            snapshot=snapshot,
            span_updates=tuple(updates),
            merged_span_logits=merged,
            validated_public_score_count=validated_public_scores,
        )

    def close(self) -> None:
        """Clear the owned reference session. Calling twice is harmless."""
        if self._closed:
            return
        self.model.clear_session(self.session_id)  # type: ignore[attr-defined]
        self._closed = True

    def __enter__(self) -> StreamingSpanObserver:
        return self

    def __exit__(self, _exc_type: object, _exc: object, _traceback: object) -> None:
        self.close()


def observer_record_json(record: ObservedAppend) -> str:
    """Serialize one observed append, primarily for debug assertions."""
    return json.dumps(record.to_dict(), ensure_ascii=False)


__all__ = [
    "ObservedAppend",
    "ObserverInvariantError",
    "PINNED_GLINER_VERSION",
    "StreamingSpanObserver",
    "observer_record_json",
]
